name: Dependabot automerge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6.0
        with:
          target: minor
          command: "squash and merge"
          github-token: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}